# Generated by Django 4.2.27 on 2025-12-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Poste', models.CharField(max_length=100)),
                ('Salaire', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
