# Generated by Django 4.2.17 on 2025-12-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='Date_Embauche',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='Prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='Telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
